[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "reunion service helmet next scorpion behind rescue number season stool fancy chalk image sentence erosion negative citizen humble peasant turkey addict know office marriage"
